package _04_spot_the_error;

import java.util.Random;

public class FixTheRandom {

	// This program is supposed to get a random number between 5 and 10 and print a different message for each number.
	// BUT it's not working. If you don't believe me, try running it.
	// Change ONE line of code to fix this program.
	
	// want me to review any concepts? questions?
	//I though that numnber would randomly get a #
	// it does ... but the range of possible numbers
	// it currently gets doesn't match the range
	// tested below.  so first let's understand the range
	// being generated.  look at line 22 and i'll explan
	
	public static void main(String[] args) {
		
		Random random = new Random();
		
		int numnber = random.nextInt(6) + 5;
		// so nextInt(6) generates 6 possible numbers
		//  which are in range 0 ... 5
		// THEN add 5 to the number generated by nextInt()
		// and you get the range 5 ... 10
		// does that make sense?yes
		
		
		// but now it generates numbers in range 0..10
		// try again?  or want me to show you?i need help
		
		// nextInt(5) will generate a number between 0 and 4
		// .. so that's 5 possible numbers
		// let's say I changed it to
		// nextInt(10) ... what possible numbers would it
		// generate? 0 - 9 correct.  now let's look at
		// the code below

		// what possible numbers is this code expecting
		// to see? i mean what list of numbers? 5 6 7 8 9 10
		// perfect.  now as you noticed, those are 6 numbers.
		// now we want to manipulate nextInt() to come up
		// with that exact range of numbers.  let's consider
		// 2 aspects to that problem.
		// first, it should be 6 possible numbers.
		// remember nextInt(5) generated 5 possible numbers
		// so what do we want to change nextInt(5) to?
		// perfect.
		// second, it now generates numbers 0...5
		// BUT we want 5...10.  Do you see an easy fix to that?
		// good thought but no.  another idea?no
		// ok.  lets look at the pattern 0...5 vs 5...10
		// the lowest values are 0 in 0...5 and 5 in 5...10
		// what simple math can you do to 0 to get to 5?
		//+5 yep now where on line 22 should you add +5?
		// good try, but that's really nextInt(11)
	// it works as intended!  questions?no			
		
		if (numnber == 5) {
			System.out.println("FIVE");
		} else if (numnber == 6) {
			System.out.println("SIX");
		} else if (numnber == 7) {
			System.out.println("SEVEN");
		} else if (numnber == 8) {
			System.out.println("EIGHT");
		} else if (numnber == 9) {
			System.out.println("NINE");
		} else if (numnber == 10) {
			System.out.println("TEN");
		}
	}
	
	
}
